package ImgPanel;

import java.awt.*;
import java.io.*;
import javax.imageio.*;
import javax.swing.*;

/**
 *
 * @author Hitendra
 */
public class ForProf extends javax.swing.JPanel {

    /**
     * Creates new form ForProf
     */
    Image im;

    public ForProf() {
        //initComponents();
    }
    int[] a = {170, 177, 123, 93};
    int[] b = {186, 200, 138, 82};
    int index = 2;

    public void paintComponent(Graphics g) {
        g.drawImage(im, 0, 0, a[index], b[index], this);
    }

    public void setImg(String path, int index) {
        try {
            this.index = index;
            FileInputStream fi = new FileInputStream(path);
            im = ImageIO.read(fi);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "" + ex.getMessage());
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
