
package ImgPanel;

import java.awt.Graphics;
import java.awt.Image;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Hitendra
 */
public class MainImg extends javax.swing.JPanel {

    Image im;

    public MainImg() {
        /*try {
            FileInputStream fi = new FileInputStream(System.getProperty("user.dir")+"\\resource\\main.jpg");
            im = ImageIO.read(fi);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ""+ex.getMessage());
        }*/
        initComponents();
    }
   
    public void paintComponent(Graphics g) {
        g.drawImage(im, 0, 0, this);
    }
    
    public void setImg(String path){
        try {
            FileInputStream fi = new FileInputStream(path);
            im = ImageIO.read(fi);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ""+ex.getMessage());
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
